SYMBOLS=PEPEUSDC,FETUSDC
BTC_SYMBOL=BTCUSDC

USE_BTC_FILTER=false

LOOKBACK_BARS=18
SETUP_BARS=6
COMPRESSION_BARS=4

ABSORPTION_MIN_COUNT=2
ABSORPTION_DELTA_RATIO_MAX=-0.20
ABSORPTION_MAX_DOWN_MOVE_PCT=0.0035

ACCUMULATION_MIN_COUNT=2
ACCUMULATION_BUY_RATIO_MIN=0.62
ACCUMULATION_DELTA_RATIO_MIN=0.18
ACCUMULATION_MAX_MOVE_PCT=0.0035

COMPRESSION_RANGE_PCT_MAX=0.0045
COMPRESSION_AVG_RANGE_PCT_MAX=0.0035

TRIGGER_CHANGE_PCT_MIN=0.0035
TRIGGER_RANGE_PCT_MIN=0.0045
TRIGGER_CLOSE_POS_MIN=0.75
TRIGGER_VOLUME_VS_SETUP_AVG_MIN=1.8
TRIGGER_BUY_RATIO_MIN=0.55
TRIGGER_DELTA_RATIO_MIN=0.05

MIN_SETUP_QUOTE_VOLUME_SUM=12000
MIN_TRIGGER_QUOTE_VOLUME=3000
MIN_AVG_TRADE_QUOTE=80

ALLOW_MULTIPLE_SIGNALS_PER_SYMBOL=true
COOLDOWN_BARS_AFTER_SIGNAL=6
DEBUG_REJECTIONS=false
