SYMBOLS=BTCUSDC,ETHUSDC,SOLUSDC,BNBUSDC,XRPUSDC,ADAUSDC,DOGEUSDC,LINKUSDC,AVAXUSDC,ATOMUSDC,NEARUSDC,INJUSDC,FETUSDC,HBARUSDC,UNIUSDC

DB_HOST=db
DB_PORT=5432
DB_NAME=pumpdb
DB_USER=pumpuser
DB_PASSWORD=

CANDLES_TABLE=public.candles_5m
SIGNAL_TABLE=public.accum_signals

POLL_SEC=5
MAX_SYMBOLS_PER_CYCLE=300

ANCHOR_SYMBOL=BTCUSDC
BTC_SYMBOL=BTCUSDC
BTC_LOOKBACK_BARS=3
BTC_KILL_DUMP_PCT=-0.008
BTC_KILL_PUMP_PCT=0.012

ALT_GREEN_ON=0.62
ALT_GREEN_OFF=0.55
ALT_GREEN_MIN_ALTS=10
ALT_GREEN_CACHE_SEC=15
ALT_GREEN_MOVE=0.002
ALT_EXCLUDE_SYMBOLS=BTCUSDC,USDCUSDT,FDUSDUSDC,TUSDUSDC,USDPUSDC

LEADER_SYMBOLS=ETHUSDC,SOLUSDC,BNBUSDC,XRPUSDC,ADAUSDC,DOGEUSDC,LINKUSDC,AVAXUSDC
LEADER_MIN_GREEN=5
LEADER_GREEN_MOVE=0.002

ACC_LOOKBACK_BARS=24
ACC_RECENT_BARS_FOR_SIGNAL=3

ACC_RANGE_MAX_PCT=0.035
ACC_SUPPORT_TOUCHES_MIN=2
ACC_SUPPORT_TOUCHES_MAX=4
SUPPORT_TOUCH_TOLERANCE_PCT=0.003
SUPPORT_DEFENSE_CLOSE_MIN_PCT=0.0015
TOUCH_BUY_RATIO_MIN=0.52

COMPRESSION_RECENT_BARS=6
COMPRESSION_PREV_BARS=6
COMPRESSION_FACTOR_MAX=0.90

REQUIRE_HIGHER_LOWS=false
HIGHER_LOWS_BARS=5
HIGHER_LOWS_MIN_COUNT=3

SWEEP_LOOKBACK_BARS=3
SWEEP_BELOW_SUPPORT_PCT=0.003
SWEEP_RECLAIM_CLOSE_ABOVE_SUPPORT=true

MIN_BOUNCE_FROM_SUPPORT_PCT=0.004
RESISTANCE_TOUCH_TOLERANCE_PCT=0.004
RESISTANCE_TESTS_MIN=1

MIN_QUOTE_VOLUME_SUM=50000
VOLUME_DRYUP_TOUCH_VS_AVG_MAX=1.10

ACCUM_SIGNAL_NAME=ACCUM_PHASE
ACCUM_SIGNAL_SOURCE=ACCUM_V2
